name: Foxy

on: [push, pull_request]


jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: foxy
            ROS_REPO: testing
            UPSTREAM_WORKSPACE: 'github:fzi-forschungszentrum-informatik/schunk_svh_library#main'
            ROSDEP_SKIP_KEYS: 'schunk_svh_library'
          - ROS_DISTRO: foxy
            ROS_REPO: main
            UPSTREAM_WORKSPACE: 'github:fzi-forschungszentrum-informatik/schunk_svh_library#main'
            ROSDEP_SKIP_KEYS: 'schunk_svh_library'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
